# Generated by Django 5.0.6 on 2024-06-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('administrative_unit', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquisition_date', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('documentation', models.TextField()),
            ],
        ),
    ]
