# Generated by Django 5.0.6 on 2024-06-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
